### PR TITLE
Fix OutOfMemoryError

### PR DESCRIPTION
**Pull request by IAmFunkyFrog**
On my old android device (Redmi Note 5A, Android 7.1.2) I faced the problem that the application crashes immediately after entering it.
I got this exception in Android Studio:
<pre>
E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: ru.spbu.depnav, PID: 3665
    java.lang.OutOfMemoryError: Failed to allocate a 4194316 byte allocation with 1130336 free bytes and 1103KB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:890)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:867)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:834)
        at ovh.plrapps.mapcompose.ui.state.TileCanvasState$special$$inlined$map$1$2.emit(Emitters.kt:224)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAll(Channels.kt:30)
        at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collect$2.invokeSuspend(ChannelFlow.kt:123)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collect$2.invoke(ChannelFlow.kt)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collect$2.invoke(ChannelFlow.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at kotlinx.coroutines.flow.internal.ChannelFlow.collect$suspendImpl(ChannelFlow.kt:122)
        at kotlinx.coroutines.flow.internal.ChannelFlow.collect(ChannelFlow.kt)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect$suspendImpl(ChannelFlow.kt:173)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collect(ChannelFlow.kt)
        at ovh.plrapps.mapcompose.ui.state.TileCanvasState$special$$inlined$map$1.collect(SafeCollector.common.kt:113)
        at kotlinx.coroutines.flow.FlowKt__ReduceKt.single(Reduce.kt:179)
        at kotlinx.coroutines.flow.FlowKt.single(Unknown Source)
        at ovh.plrapps.mapcompose.core.TileCollector$worker$1$bitmapForLayers$1$1.invokeSuspend(TileCollector.kt:135)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
    	Suppressed: java.lang.OutOfMemoryError: Failed to allocate a 4194316 byte allocation with 1130952 free bytes and 1104KB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:890)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:867)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:834)
        at ovh.plrapps.mapcompose.ui.state.TileCanvasState$special$$inlined$map$1$2.emit(Emitters.kt:224)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
        		... 5 more
</pre>

Troubleshooting was taken from [here](https://stackoverflow.com/questions/32244851/androidjava-lang-outofmemoryerror-failed-to-allocate-a-23970828-byte-allocatio).

### CODE REVIEW

**Comment by IAmFunkyFrog** [comment]
[Log.txt](https://github.com/TimPushkin/DepNav/files/8672105/Log.txt) - file containing the full log from Android Studio

**Comment by TimPushkin** [comment]
Thanks for the report and for the proposed fix! I'll first investigate if I can reduce the size of the resources that the app loads from memory (the bitmaps especially) and if that won't be enough, I'll accept this PR.

**Comment by TimPushkin** [comment]
A quick update as I'm working on the fix: it seems like splitting the map into smaller tiles and dividing it onto several different levels of detail fixes the memmory issues on older Android devices.

There are still things to be done, but I'll most likely fix the issue this way.

**Comment by TimPushkin** [comment]
Tried to fix this in [e489052](https://github.com/TimPushkin/DepNav/commit/e489052a6f840305ad40240132b5509615ea0bb4).

**Comment by TimPushkin** [comment]
I'm preparing #16 to fix this issue, so closing this. Thanks again for the report!

**Pull request closed without merging**
